export const BREAKING_NEWS = [
  'THE LEAGUE IS LIVE. WHERE IS YOUR CARD?',
  "I'M 94 OVR. BEAT ME.",
  'CALL THE NEXT FIXTURE OR SIT DOWN.',
  'YOUR OVR IS PUBLIC. ACT LIKE IT.',
  'ARSENAL OPENED AT HOME TO COVENTRY. DID YOU CALL IT?',
  'POST THE CARD. RUIN THE GROUP CHAT.',
];

export const PLAYERS = [
  {
    src: 'https://crests.football-data.org/57.png',
    alt: 'Arsenal crest',
    flag: 'ARS',
    name: 'SAKA',
    country: 'Arsenal',
    verdict: 'TITLE DEFENCE',
    hook: 'Arsenal opened at home. You said they were going back-to-back. Put it on a card.',
    cardHook: 'Call Arsenal →',
    href: '/premier-league',
    accent: '#EF0107',
    border: '#EF0107',
  },
  {
    src: 'https://crests.football-data.org/65.png',
    alt: 'Manchester City crest',
    flag: 'MCI',
    name: 'HAALAND',
    country: 'Manchester City',
    verdict: 'POST-PEP ERA',
    hook: 'No Pep. Still Haaland. 30+ or you were chatting.',
    cardHook: 'Call City →',
    href: '/premier-league',
    accent: '#6CABDD',
    border: '#6CABDD',
  },
  {
    src: 'https://crests.football-data.org/64.png',
    alt: 'Liverpool crest',
    flag: 'LIV',
    name: 'SALAH',
    country: 'Liverpool',
    verdict: 'IRAOLA BALL',
    hook: 'Salah under Iraola. You already have a take. Lock it before kickoff.',
    cardHook: 'Call Liverpool →',
    href: '/premier-league',
    accent: '#C8102E',
    border: '#C8102E',
  },
  {
    src: 'https://crests.football-data.org/61.png',
    alt: 'Chelsea crest',
    flag: 'CHE',
    name: 'PALMER',
    country: 'Chelsea',
    verdict: 'ALONSO PROJECT',
    hook: 'Alonso at Chelsea. Palmer decides it. Call west London or stay quiet.',
    cardHook: 'Call Chelsea →',
    href: '/premier-league',
    accent: '#034694',
    border: '#034694',
  },
  {
    src: 'https://crests.football-data.org/66.png',
    alt: 'Manchester United crest',
    flag: 'MUN',
    name: 'BRUNO',
    country: 'Manchester United',
    verdict: 'CARRICK BRIEF',
    hook: 'United at Hull. Statement win or another year of excuses.',
    cardHook: 'Call United →',
    href: '/premier-league',
    accent: '#DA291C',
    border: '#DA291C',
  },
  {
    src: 'https://crests.football-data.org/1076.png',
    alt: 'Coventry City crest',
    flag: 'COV',
    name: 'LAMPARD',
    country: 'Coventry City',
    verdict: 'SKY BLUE RETURN',
    hook: 'Coventry at the Emirates after 25 years. Shock of the season or cannon fodder.',
    cardHook: 'Call Coventry →',
    href: '/premier-league',
    accent: '#77BBFF',
    border: '#77BBFF',
  },
];

export const COUNTRIES = [
  { flag: 'ARS', name: 'Arsenal', group: 'PL', fifa: 'ARS', qualified: 'Defending champions', color: '#EF0107', verdict: 'TITLE DEFENCE', story: 'You called the repeat. Now it is on a card.', href: '/premier-league' },
  { flag: 'MCI', name: 'Manchester City', group: 'PL', fifa: 'MCI', qualified: 'Champions League', color: '#6CABDD', verdict: 'NEW ERA', story: 'No Pep. Same Haaland. Call it.', href: '/premier-league' },
  { flag: 'LIV', name: 'Liverpool', group: 'PL', fifa: 'LIV', qualified: 'Champions League', color: '#C8102E', verdict: 'IRAOLA BALL', story: 'Iraola ball at Anfield. You already have a take.', href: '/premier-league' },
  { flag: 'MUN', name: 'Manchester United', group: 'PL', fifa: 'MUN', qualified: 'Champions League', color: '#DA291C', verdict: 'AWAY AT HULL', story: 'United at Hull. Statement or another excuse.', href: '/premier-league' },
  { flag: 'AVL', name: 'Aston Villa', group: 'PL', fifa: 'AVL', qualified: 'Champions League', color: '#670E36', verdict: 'EMERY MACHINE', story: 'Villa in the title chat. Prove you believed early.', href: '/premier-league' },
  { flag: 'CHE', name: 'Chelsea', group: 'PL', fifa: 'CHE', qualified: 'Premier League', color: '#034694', verdict: 'WEST LONDON', story: 'Alonso. Palmer. Put a number on it.', href: '/premier-league' },
  { flag: 'TOT', name: 'Tottenham Hotspur', group: 'PL', fifa: 'TOT', qualified: 'Premier League', color: '#132257', verdict: 'NORTH LONDON', story: 'Spurs. You know the bit. Still call it.', href: '/premier-league' },
  { flag: 'NEW', name: 'Newcastle United', group: 'PL', fifa: 'NEW', qualified: 'Premier League', color: '#241F20', verdict: 'ST JAMES NIGHT', story: 'St James. Big nights. Bigger takes.', href: '/premier-league' },
  { flag: 'COV', name: 'Coventry City', group: 'PL', fifa: 'COV', qualified: 'Promoted', color: '#77BBFF', verdict: 'SKY BLUES', story: 'Back after 25 years. Shock of the season or cannon fodder.', href: '/premier-league' },
  { flag: 'IPS', name: 'Ipswich Town', group: 'PL', fifa: 'IPS', qualified: 'Promoted', color: '#0044AA', verdict: 'TRACTOR BOYS', story: 'Ipswich are back. Call survival or a movie.', href: '/premier-league' },
  { flag: 'HUL', name: 'Hull City', group: 'PL', fifa: 'HUL', qualified: 'Promoted', color: '#F5A623', verdict: 'TIGERS RETURN', story: 'Hull vs United at home. Giant-killing or reality.', href: '/premier-league' },
  { flag: 'SUN', name: 'Sunderland', group: 'PL', fifa: 'SUN', qualified: 'Europa League', color: '#EB172B', verdict: 'BLACK CATS', story: 'Sunderland in Europe. Say it with your chest.', href: '/premier-league' },
];
