export const BREAKING_NEWS = [
  'WORLD CUP 2026 NORTH AMERICA: 48 teams. 1 trophy. Infinite delusions.',
  'FOOTBALL IQ: Build your reputation, one matchday decision at a time.',
  'COLLECT VERDICTS: Every fixture graded yields a custom Match Card.',
  'UPCOMING MATCHES: Select a game, submit takes, and wait for results.',
  'VIRAL CARD ALBUM: Complete match predictions, claim cards, and share.',
  'LIVE NOW: Matches are underway. Check live group standings on the Hub.',
];

export const PLAYERS = [
  {
    src: '/images/messi.jpeg',
    alt: 'Lionel Messi World Cup Ceremony',
    flag: '🇦🇷',
    name: 'MESSI',
    country: 'Argentina',
    verdict: 'CORONATION CONFIRMED',
    hook: 'He lifted the trophy in Qatar. Yet, half the football world is still filing appeals. Grade whether the 2026 script is already written.',
    cardHook: 'Predict Argentina fixture →',
    href: '/world-cup-hub',
    accent: '#43AAFF',
    border: '#43AAFF',
  },
  {
    src: '/images/ronaldo.jpg',
    alt: 'Cristiano Ronaldo celebration',
    flag: '🇵🇹',
    name: 'RONALDO',
    country: 'Portugal',
    verdict: '47 FACTOS PENDING',
    hook: 'Benched in Qatar. Now compiling desert stats to defend an empire. Grade the final appeal of Cristiano\'s legacy before the final whistle.',
    cardHook: 'Predict Portugal fixture →',
    href: '/world-cup-hub',
    accent: '#E42313',
    border: '#E42313',
  },
  {
    src: '/images/neymar.jpeg',
    alt: 'Neymar Jr Brazil',
    flag: '🇧🇷',
    name: 'NEYMAR',
    country: 'Brazil',
    verdict: 'PERMANENTLY INJURED',
    hook: '1,847 career days lost to injury. A suspicious number coinciding with Rio carnival season. Summon the Samba Prince to the match day dock.',
    cardHook: 'Predict Brazil fixture →',
    href: '/world-cup-hub',
    accent: '#009739',
    border: '#009739',
  },
  {
    src: '/images/media__1781514653491.jpg',
    alt: 'Kylian Mbappe France',
    flag: '🇫🇷',
    name: 'MBAPPÉ',
    country: 'France',
    verdict: 'VETO POWER REVOKED',
    hook: 'Vetoed two national coaches. Demanded a sovereign buyout. Then walked away on a free. Read the tactical prophecy of his Madrid era.',
    cardHook: 'Predict France fixture →',
    href: '/world-cup-hub',
    accent: '#002395',
    border: '#002395',
  },
  {
    src: '/images/stadium_bg.webp',
    alt: 'Erling Haaland Norway',
    flag: '🇳🇴',
    name: 'HAALAND',
    country: 'Norway',
    verdict: 'GHOST IN BIG GAMES',
    hook: 'Scored 50+ goals in a calendar year. Vanished in three consecutive finals. Generational phenomenon or tap-in merchant?',
    cardHook: 'Predict Norway fixture →',
    href: '/world-cup-hub',
    accent: '#0EA5E9',
    border: '#0EA5E9',
  },
  {
    src: '/images/debate_bg.webp',
    alt: 'Jude Bellingham England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    name: 'BELLINGHAM',
    country: 'England',
    verdict: 'PR CAMPAIGN PENDING',
    hook: 'Broke records, won Madrid crowns, celebrated with arms wide open. Yet, went silent in the Euro knockout stages. Summon him.',
    cardHook: 'Predict England fixture →',
    href: '/world-cup-hub',
    accent: '#E0A96D',
    border: '#E0A96D',
  },
  {
    src: '/images/chaos_crowd.webp',
    alt: 'Vinicius Jr Brazil',
    flag: '🇧🇷',
    name: 'VINÍCIUS',
    country: 'Brazil',
    verdict: 'BALLON D\'OR VETO',
    hook: 'Dribbled past whole defenses, declared himself king. Yet, boycotted the Ballon d\'Or ceremony after a shocking veto.',
    cardHook: 'Predict Brazil fixture →',
    href: '/world-cup-hub',
    accent: '#FBBF24',
    border: '#FBBF24',
  },
  {
    src: '/images/last_dance.webp',
    alt: 'Harry Kane England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    name: 'KANE',
    country: 'England',
    verdict: 'THE ETERNAL CURSE',
    hook: 'Scored 400+ career goals, broke German scoring records, yet still has zero trophies. The curse is mathematically proven. Summon him.',
    cardHook: 'Predict England fixture →',
    href: '/world-cup-hub',
    accent: '#64748B',
    border: '#64748B',
  },
];

export const COUNTRIES = [
  { flag: '🇦🇷', name: 'Argentina',    color: '#43AAFF', story: 'Crowned champions in Qatar. Now, the world awaits to see if the crown can survive the thin air of North America.',  verdict: 'CHAMPIONS',         href: '/world-cup-hub' },
  { flag: '🇧🇷', name: 'Brazil',       color: '#009739', story: 'Five stars on the chest. One eternal prince in exile. Twenty-four years of waiting for the beautiful game to return.',          verdict: 'SAMBA EXILE',  href: '/world-cup-hub' },
  { flag: '🇵🇹', name: 'Portugal',     color: '#E42313', story: 'Quarter-final tears, social media campaigns, and tacticians in denial. Can they build a dynasty without the patriarch?', verdict: 'POST-HERO ERA',    href: '/world-cup-hub' },
  { flag: '🇫🇷', name: 'France',       color: '#002395', story: 'A penalty shootout away from back-to-back crowns. With their new captain holding Madrid veto powers, will they implode?',       verdict: 'ROYAL MUTINY',      href: '/world-cup-hub' },
  { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England',      color: '#CF142B', story: 'Seven historic shootout heartbreaks. Yet, the choir sings of it coming home. Rate the bottle risk of the Three Lions.', verdict: 'BOTTLE CLINIC',  href: '/world-cup-hub' },
  { flag: '🇩🇪', name: 'Germany',      color: '#222',    story: 'Back-to-back group stage exits. The legendary Prussian efficiency has broken down. Can the new generation repair the engine?',     verdict: 'ENGINE FAILURE',    href: '/world-cup-hub' },
  { flag: '🇪🇸', name: 'Spain',        color: '#AA151B', story: 'Conquered Europe with teenage wingers and direct transition. Can their youth academy audacity work in the Rose Bowl?',        verdict: 'AUDACITY TEST',  href: '/world-cup-hub' },
  { flag: '🇳🇱', name: 'Netherlands',  color: '#FF6600', story: 'Total football. Flawless geometry. Yet, always the bridesmaids. Will they finally turn tactical poetry into gold?',      verdict: 'POSSESSION POETS',   href: '/world-cup-hub' },
  { flag: '🇺🇾', name: 'Uruguay',      color: '#5B9BD5', story: 'Biting defenders, high-press warfare, and absolute grit. The court rules their brand of football permanently chaotic.',        verdict: 'CHAOS APPROVED',  href: '/world-cup-hub' },
  { flag: '🇲🇦', name: 'Morocco',      color: '#C1272D', story: 'The historic semi-finalists of 2022. No longer underdogs, they return to prove their fairy tale was pure ball knowledge.',      verdict: 'ATLAS SUNRISE', href: '/world-cup-hub' },
  { flag: '🇯🇵', name: 'Japan',        color: '#BC002D', story: 'Slayed giants, clean-swept the dressing room, and won the world\'s respect. The court issues a decree of supreme class.',           verdict: 'SUPREME CLASS',    href: '/world-cup-hub' },
  { flag: '🇸🇦', name: 'Saudi Arabia', color: '#006C35', story: 'Slayed Messi on day three of Qatar. A result that still defies logical explanation. Can they cook another miracle?', verdict: 'GREEN MIRACLE', href: '/world-cup-hub' },
];
