export const BREAKING_NEWS = [
  'PREMIER LEAGUE 2026/27: Arsenal host Coventry City to open the season on 21 August.',
  'FOOTBALL IQ: Build your reputation, one matchweek prediction at a time.',
  'COLLECT VERDICTS: Every fixture graded yields a custom VAR Match Card.',
  'LOCK IN NOW: Predictions close at kickoff.',
  'VIRAL CARD ALBUM: Predict matches, claim cards, and share your binder.',
  'TITLE RACE: 38 matchweeks, 380 games. Lock in your Premier League takes.',
];

export const PLAYERS = [
  {
    src: 'https://crests.football-data.org/57.png',
    alt: 'Arsenal crest',
    flag: 'ARS',
    name: 'SAKA',
    country: 'Arsenal',
    verdict: 'TITLE DEFENCE',
    hook: 'Arsenal open at home to Coventry. Grade whether the champions can go back-to-back in 2026/27.',
    cardHook: 'Predict Arsenal fixture →',
    href: '/premier-league',
    accent: '#EF0107',
    border: '#EF0107',
  },
  {
    src: 'https://crests.football-data.org/65.png',
    alt: 'Manchester City crest',
    flag: 'MCI',
    name: 'HAALAND',
    country: 'Manchester City',
    verdict: 'POST-PEP ERA',
    hook: 'City start without Guardiola. Grade whether Haaland still decides the title race.',
    cardHook: 'Predict Manchester City fixture →',
    href: '/premier-league',
    accent: '#6CABDD',
    border: '#6CABDD',
  },
  {
    src: 'https://crests.football-data.org/64.png',
    alt: 'Liverpool crest',
    flag: 'LIV',
    name: 'SALAH',
    country: 'Liverpool',
    verdict: 'IRAOLA BALL',
    hook: 'Liverpool open at Newcastle under Andoni Iraola. Grade the Anfield reset.',
    cardHook: 'Predict Liverpool fixture →',
    href: '/premier-league',
    accent: '#C8102E',
    border: '#C8102E',
  },
  {
    src: 'https://crests.football-data.org/61.png',
    alt: 'Chelsea crest',
    flag: 'CHE',
    name: 'PALMER',
    country: 'Chelsea',
    verdict: 'ALONSO PROJECT',
    hook: 'Chelsea start at Fulham under Xabi Alonso. Grade the west London reset.',
    cardHook: 'Predict Chelsea fixture →',
    href: '/premier-league',
    accent: '#034694',
    border: '#034694',
  },
  {
    src: 'https://crests.football-data.org/66.png',
    alt: 'Manchester United crest',
    flag: 'MUN',
    name: 'BRUNO',
    country: 'Manchester United',
    verdict: 'CARRICK BRIEF',
    hook: 'United open at Hull. Grade whether the Carrick era starts with a statement.',
    cardHook: 'Predict Manchester United fixture →',
    href: '/premier-league',
    accent: '#DA291C',
    border: '#DA291C',
  },
  {
    src: 'https://crests.football-data.org/1076.png',
    alt: 'Coventry City crest',
    flag: 'COV',
    name: 'LAMPARD',
    country: 'Coventry City',
    verdict: 'SKY BLUE RETURN',
    hook: 'Coventry are back after 25 years. They open at the Emirates. Grade the shock.',
    cardHook: 'Predict Coventry fixture →',
    href: '/premier-league',
    accent: '#77BBFF',
    border: '#77BBFF',
  },
];

export const COUNTRIES = [
  { flag: 'ARS', name: 'Arsenal', group: 'PL', fifa: 'ARS', qualified: 'Defending champions', color: '#EF0107', verdict: 'TITLE DEFENCE', story: 'Arsenal host Coventry City on opening night as they start the title defence.', href: '/premier-league' },
  { flag: 'MCI', name: 'Manchester City', group: 'PL', fifa: 'MCI', qualified: 'Champions League', color: '#6CABDD', verdict: 'NEW ERA', story: 'Life after Guardiola begins at home to Bournemouth.', href: '/premier-league' },
  { flag: 'LIV', name: 'Liverpool', group: 'PL', fifa: 'LIV', qualified: 'Champions League', color: '#C8102E', verdict: 'IRAOLA BALL', story: 'Liverpool travel to Newcastle on Sunday of matchweek 1.', href: '/premier-league' },
  { flag: 'MUN', name: 'Manchester United', group: 'PL', fifa: 'MUN', qualified: 'Champions League', color: '#DA291C', verdict: 'AWAY AT HULL', story: 'United open at newly promoted Hull City.', href: '/premier-league' },
  { flag: 'AVL', name: 'Aston Villa', group: 'PL', fifa: 'AVL', qualified: 'Champions League', color: '#670E36', verdict: 'EMERY MACHINE', story: 'Villa open away at Brighton on Sunday.', href: '/premier-league' },
  { flag: 'CHE', name: 'Chelsea', group: 'PL', fifa: 'CHE', qualified: 'Premier League', color: '#034694', verdict: 'WEST LONDON', story: 'Alonso’s Chelsea start at Craven Cottage on Monday night.', href: '/premier-league' },
  { flag: 'TOT', name: 'Tottenham Hotspur', group: 'PL', fifa: 'TOT', qualified: 'Premier League', color: '#132257', verdict: 'NORTH LONDON', story: 'Spurs open away at Brentford on Saturday evening.', href: '/premier-league' },
  { flag: 'NEW', name: 'Newcastle United', group: 'PL', fifa: 'NEW', qualified: 'Premier League', color: '#241F20', verdict: 'ST JAMES NIGHT', story: 'Newcastle host Liverpool in the pick of Sunday’s fixtures.', href: '/premier-league' },
  { flag: 'COV', name: 'Coventry City', group: 'PL', fifa: 'COV', qualified: 'Promoted', color: '#77BBFF', verdict: 'SKY BLUES', story: 'Championship winners open at Arsenal after 25 years away.', href: '/premier-league' },
  { flag: 'IPS', name: 'Ipswich Town', group: 'PL', fifa: 'IPS', qualified: 'Promoted', color: '#0044AA', verdict: 'TRACTOR BOYS', story: 'Ipswich host Sunderland on the opening Saturday.', href: '/premier-league' },
  { flag: 'HUL', name: 'Hull City', group: 'PL', fifa: 'HUL', qualified: 'Promoted', color: '#F5A623', verdict: 'TIGERS RETURN', story: 'Hull host Manchester United in their first Premier League home game.', href: '/premier-league' },
  { flag: 'SUN', name: 'Sunderland', group: 'PL', fifa: 'SUN', qualified: 'Europa League', color: '#EB172B', verdict: 'BLACK CATS', story: 'Sunderland open at Portman Road.', href: '/premier-league' },
];
